### ISSUE TITLE
Error with numpy in pycafe

### ISSUE THREAD

**Issue by haesleinhuepf** [haesleinhuepf/stackview#52]
Reported here:
https://x.com/maartenbreddels/status/1811113969832137005

Code:
https://py.cafe/maartenbreddels/stackview-clusterplot

Error:
```
File "/lib/python3.11/site-packages/stackview/_image_widget.py", line 83, in <listcomp>
    return np.asarray([lut[:, c].take(image.astype(np.int64)) for c in range(0, 3)]).swapaxes(0, 2).swapaxes(1, 0) * 255
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by haesleinhuepf** [comment]
Same page, different error:

![image](https://github.com/haesleinhuepf/stackview/assets/12660498/ad6734bf-77b6-4e29-9e30-067fda139bc1)

```
Traceback (most recent call last):
  File "/lib/python3.11/jc/solara.py", line 191, in run
    import solara.server.starlette
  File "/lib/python3.11/site-packages/solara/server/starlette.py", line 52, in <module>
    from . import app as appmod
  File "/lib/python3.11/site-packages/solara/server/app.py", line 491, in <module>
    apps["__default__"] = AppScript(os.environ.get("SOLARA_APP", "solara.website.pages:Page"))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/solara/server/app.py", line 73, in __init__
    app = self._execute()
          ^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/solara/server/app.py", line 123, in _execute
    routes = [solara.autorouting._generate_route_path(self.path, first=True, initial_namespace=initial_namespace)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/solara/autorouting.py", line 516, in _generate_route_path
    module = source_to_module(subpath, initial_namespace=initial_namespace)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/solara/autorouting.py", line 38, in source_to_module
    exec(ast, mod.__dict__)
  File "/home/pyodide/project-files/app.py", line 5, in <module>
    from skimage.measure import regionprops_table
  File "/lib/python3.11/site-packages/skimage/measure/__init__.py", line 3, in <module>
    from ._regionprops import (regionprops, perimeter,
  File "/lib/python3.11/site-packages/skimage/measure/_regionprops.py", line 9, in <module>
    from scipy import ndimage as ndi
  File "/lib/python3.11/site-packages/scipy/__init__.py", line 189, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/scipy/ndimage/__init__.py", line 154, in <module>
    from ._interpolation import *  # noqa: F401 F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/scipy/ndimage/_interpolation.py", line 37, in <module>
    from scipy import special
  File "/lib/python3.11/site-packages/scipy/__init__.py", line 189, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/scipy/special/__init__.py", line 772, in <module>
    from . import _ufuncs
ImportError: Could not load dynamic lib: /lib/python3.11/site-packages/scipy/special/_ufuncs.cpython-311-wasm32-emscripten.so
Error: Didn't expect to load any more file_packager files!
```

**Comment by maartenbreddels** [comment]
Yeah, super annoying bug (the last one), if you modify requirements.txt, and restart server (or Settings->System Restart) you can recover from this.
I wonder if there the first issue is due to pyodide being 32bit.
